In [4]:
import pandas as pd
from student_group_maps import *
from save_load_pickle import *
from datetime import datetime

trace = pd.read_csv("../trace_data/trace.csv")
trace = trace.sort_values(by=['userID', 'time'])
trace = trace[trace.assignmentID=='day2']



def trace2code(trace):
    code_data = pd.DataFrame(columns=['teamID', 'code'])
    old_team_id = ''
    for i in tqdm(trace.index):
        if not isinstance(trace.at[i, 'code'], str):
            continue
        user_id = trace.at[i, 'userID']
        try:
            team_id = userID_teamID_maps[user_id]
        except:
            continue
        if team_id != old_team_id:
            if old_team_id:
                new_row = {"teamID": old_team_id, "code": code}
                code_data.loc[len(code_data)] = new_row
            old_team_id = team_id
        code = trace.at[i, 'code']

    code_data = code_data.sort_values(by=['teamID'])
    save_obj(code_data, 'code_data', 'results')
    
trace2code(trace)
# print(trace.head())

# def code2xml(code_data):
#     combined_code_data = pd.DataFrame(columns = ['combinedID', 'code'])
#     old_combined_team_id = ''
#     for i in code_data.index:
#         team_id = code_data.at[i, 'teamID']
#         combined_team_id = team_id[0:3]
#         if combined_team_id != old_combined_team_id:
#             if old_combined_team_id:
#                 new_row = {"combinedID": combined_team_id, "code": code}
#                 combined_code_data.loc[len(combined_code_data)]= new_row
#             old_combined_team_id = combined_team_id
#         code = code_data.at[i, 'code']
#     save_obj(combined_code_data, 'combined_code_data', 'results')

# code_data = load_obj("code_data", 'results')
# code2xml(code_data)

           id                 time           serverTime  \
18601  110020  2020-06-30 07:45:02  2020-06-30 07:45:16
18602  110021  2020-06-30 07:45:02  2020-06-30 07:45:16
18603  110022  2020-06-30 07:45:02  2020-06-30 07:45:16
18604  110023  2020-06-30 07:45:02  2020-06-30 07:45:16
18605  110024  2020-06-30 07:45:02  2020-06-30 07:45:16

                     message   data assignmentID            userID  \
18601         Logger.started     ""         day2  archit/charlotte
18602             IDE.opened     ""         day2  archit/charlotte
18603  IDE.openProjectString     ""         day2  archit/charlotte
18604      PairsDisplay.show     ""         day2  archit/charlotte
18605      IDE.toggleAppMode  false         day2  archit/charlotte

                                  projectID  \
18601                                   NaN
18602  dd9b2885-0df4-4e33-9390-399927d3a499
18603  dd9b2885-0df4-4e33-9390-399927d3a499
18604  dd9b2885-0df4-4e33-9390-399927d3a499
18605  dd9b2885-0df4-4e33-9390-399927d3a499

                                  sessionID  \
18601  62dddbf6-9986-4991-b37e-6840bba6f615
18602  62dddbf6-9986-4991-b37e-6840bba6f615
18603  62dddbf6-9986-4991-b37e-6840bba6f615
18604  62dddbf6-9986-4991-b37e-6840bba6f615
18605  62dddbf6-9986-4991-b37e-6840bba6f615

                                  browserID  \
18601  87c1745f-f918-493f-a99c-a2bdba3f71c3
18602  87c1745f-f918-493f-a99c-a2bdba3f71c3
18603  87c1745f-f918-493f-a99c-a2bdba3f71c3
18604  87c1745f-f918-493f-a99c-a2bdba3f71c3
18605  87c1745f-f918-493f-a99c-a2bdba3f71c3

                                                    code
18601                                                NaN
18602  <project name="Untitled" app="iSnap 2.1, http:...
18603                                                NaN
18604                                                NaN
18605                                                NaN

get number of example request per teamID (a_0_0, a_0_1);  (in programming task)
the amount of time they took in each request (in programming)
the gifName of the request they asked (in programming)

id, teamID, requestNumber, timeOnExample
0, a_0_0, 1, 50
1, a_0_0, 2, 30
2, a_0_0, 3, 21
3, a_0_0, 4, 30
4, a_0_1, .., ..